./tests.exe 1 0 10 15 | tee ../results/random/coctail.sort.json
./tests.exe 2 0 10 15 | tee ../results/random/selection.sort.json
./tests.exe 3 0 10 15 | tee ../results/random/insertion.sort.json
./tests.exe 4 0 10 15 | tee ../results/random/quick.sort.json
./tests.exe 5 0 10 15 | tee ../results/random/heap.sort.json
./tests.exe 6 0 10 15 | tee ../results/random/shell.sort.json
./tests.exe 1 1 10 15 | tee ../results/sorted/coctail.sort.json
./tests.exe 2 1 10 15 | tee ../results/sorted/selection.sort.json
./tests.exe 3 1 10 15 | tee ../results/sorted/insertion.sort.json
./tests.exe 4 1 10 15 | tee ../results/sorted/quick.sort.json
./tests.exe 5 1 10 15 | tee ../results/sorted/heap.sort.json
./tests.exe 6 1 10 15 | tee ../results/sorted/shell.sort.json
./tests.exe 1 2 10 15 | tee ../results/reverse/coctail.sort.json
./tests.exe 2 2 10 15 | tee ../results/reverse/selection.sort.json
./tests.exe 3 2 10 15 | tee ../results/reverse/insertion.sort.json
./tests.exe 4 2 10 15 | tee ../results/reverse/quick.sort.json
./tests.exe 5 2 10 15 | tee ../results/reverse/heap.sort.json
./tests.exe 6 2 10 15 | tee ../results/reverse/shell.sort.json
./tests.exe 1 3 10 15 | tee ../results/exceptions/coctail.sort.json
./tests.exe 2 3 10 15 | tee ../results/exceptions/selection.sort.json
./tests.exe 3 3 10 15 | tee ../results/exceptions/insertion.sort.json
./tests.exe 4 3 10 15 | tee ../results/exceptions/quick.sort.json
./tests.exe 5 3 10 15 | tee ../results/exceptions/heap.sort.json
./tests.exe 6 3 10 15 | tee ../results/exceptions/shell.sort.json
